import type { Metadata } from "next";
import CategoryBlogFeed from "@/components/CategoryBlogFeed";
import { ResourceFooter, ResourceHeader } from "@/components/ResourceChrome";

type Category={name:string;slug:string;description?:string|null;blogs_count?:number};
const siteUrl="https://www.websitedesigner.ng";
const label=(slug:string)=>slug.split("-").filter(Boolean).map(word=>word[0]?.toUpperCase()+word.slice(1)).join(" ");

async function getCategory(slug:string):Promise<Category|null>{try{const base=(process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000/api").replace(/\/$/,"");const response=await fetch(`${base}/blog-categories`,{next:{revalidate:600}});if(!response.ok)return null;const result=await response.json() as {categories:Category[]};return result.categories.find(item=>item.slug===slug)??null}catch{return null}}

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params,category=await getCategory(slug),name=category?.name??label(slug),description=category?.description?.trim()||`Read the latest ${name} articles, practical guides and expert insights from Website Designer Nigeria.`;return{title:{absolute:`${name} Articles - Tech Blog in Nigeria`},description,keywords:[`${name} Articles`,`${name} Nigeria`,`Tech Blog in Nigeria`],alternates:{canonical:`/categories/${slug}/`},robots:{index:true,follow:true},openGraph:{title:`${name} Articles - Tech Blog in Nigeria`,description,url:`/categories/${slug}/`,siteName:"Website Designer Nigeria",type:"website",images:[{url:"/images/portfolio/Accelede.png",alt:`${name} articles and guides in Nigeria`}]},twitter:{card:"summary_large_image",title:`${name} Articles`,description,images:["/images/portfolio/Accelede.png"]}}}

export default async function Page({params}:{params:Promise<{slug:string}>}){const{slug}=await params,category=await getCategory(slug),name=category?.name??label(slug),description=category?.description?.trim()||`Practical thinking, useful guidance and recent perspectives filed under ${name}.`,pageUrl=`${siteUrl}/categories/${slug}/`;const collectionSchema={"@context":"https://schema.org","@type":"CollectionPage","@id":`${pageUrl}#webpage`,name:`${name} Articles`,description,url:pageUrl,isPartOf:{"@id":`${siteUrl}/tech-blog/#blog`},about:name};const breadcrumbSchema={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:`${siteUrl}/`},{"@type":"ListItem",position:2,name:"Tech Blog",item:`${siteUrl}/tech-blog/`},{"@type":"ListItem",position:3,name,item:pageUrl}]};return <main className="resource-page collection-page category-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(collectionSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbSchema)}}/><ResourceHeader/><section className="portal-hero"><div className="shell"><p className="kicker">Technology blog category</p><h1>{name} articles and guides.</h1><p>{description}</p></div></section><section className="resource-light"><div className="shell"><CategoryBlogFeed slug={slug}/></div></section><ResourceFooter/></main>}
