import type { Metadata } from "next";
import ServicePricingTemplate, { type ServicePricingData } from "@/components/ServicePricingTemplate";
export const metadata:Metadata={title:{absolute:"Shopify Store Pricing in Nigeria - Website Designer Nigeria"},description:"Compare Shopify store design pricing in Nigeria for conversion-focused online stores, local payment integration, product setup, training and support.",keywords:["Shopify Store Pricing in Nigeria","Shopify Store Design Pricing in Nigeria","Shopify Web Development Nigeria","Shopify Website Cost Nigeria"],alternates:{canonical:"/shopify-store-pricing/"},robots:{index:true,follow:true},openGraph:{title:"Shopify Store Pricing in Nigeria - Website Designer Nigeria",description:"Compare Shopify design packages for Nigerian brands that need a polished, manageable and conversion-focused online store.",url:"/shopify-store-pricing/",siteName:"Website Designer Nigeria",type:"website",images:[{url:"/images/portfolio/azafricanstore.png",alt:"Shopify store design portfolio in Nigeria"}]},twitter:{card:"summary_large_image",title:"Shopify Store Pricing in Nigeria - Website Designer Nigeria",description:"Compare conversion-focused Shopify store design packages in Nigeria.",images:["/images/portfolio/azafricanstore.png"]}};
const data:ServicePricingData={pageClass:"shopify-pricing-page",eyebrow:"Shopify Store Design Pricing in Nigeria",title:"Shopify Stores Built",accent:"to Sell More",description:"Shopify web development in Nigeria for ambitious brands that need a polished, manageable and conversion-focused online store.",sectionLabel:"Shopify Store Design Pricing in Nigeria",sectionTitle:"Our Shopify Development Pricing Plans",sectionCopy:"How much does a Shopify website design cost in Nigeria? Compare our Shopify store design pricing and choose the right starting point.",plans:[
{name:"Starter",ngn:"500,000",usd:"500",features:["Custom Domain Integration","Premium Theme Customization","Up to 50 Products Setup","Payment Gateway Integration","Mobile Responsive Design","Basic SEO Setup","1 Week Training & Support"]},
{name:"Professional",ngn:"700,000",usd:"700",popular:true,features:["Custom Domain & Business Email","Custom Theme Development","Up to 200 Products Setup","Multiple Payment Gateways","Advanced SEO Optimization","Social Media Integration","Email Marketing Setup","Analytics & Tracking Setup","1 Month Training & Support"]},
{name:"Enterprise",ngn:"XXX,XXX",usd:"XXX",features:["Fully Custom Store Design","Unlimited Products Setup","Custom App Development","Advanced Marketing Automation","Multi-Currency & Multi-Language","Priority Support & Maintenance","Dedicated Account Manager","Custom Integrations","Ongoing Training & Support"]}],
faqs:[["What about the Shopify subscription?","The monthly Shopify subscription is not included in our packages and will be your responsibility. You will choose and pay for your preferred Shopify plan directly with Shopify, and we will guide you through selecting and setting it up."],["Do I need technical knowledge to manage my Shopify store?","Not at all. Shopify is designed for non-technical users, and every package includes training on adding products, managing orders and updating your store."],["Can I add more products after my store is built?","Yes. Package product limits refer only to the initial setup we handle. After launch, you can add unlimited products yourself at no additional setup cost."],["What payment methods can customers use on my Shopify store?","We can integrate suitable gateways such as Shopify Payments, Stripe, PayPal, Paystack and Flutterwave, depending on your market and eligibility."],["How long does it take to build a Shopify store?","Starter usually takes 1-2 weeks, Professional 2-4 weeks and Enterprise 4-6 weeks depending on customisation complexity."],["What support do you provide after the store goes live?","All packages include post-launch support, ranging from one week to ongoing support for Enterprise clients."]],benefits:[["A Shopify store should be easy to buy from—and easy to run.","Our Shopify design process balances brand presentation, product discovery, mobile conversion and the everyday tasks your team handles after launch."],["Conversion-ready storefronts","Clear navigation, product pages and checkout journeys help customers buy with confidence."],["Nigerian payments","We configure appropriate local and international payment options for your audience."],["Training included","Your team learns how to manage products, orders, promotions and essential store content."]]};
export default function Page(){return <ServicePricingTemplate data={data}/>}








