import type { Metadata } from "next";
import ServicePricingTemplate,{type ServicePricingData} from "@/components/ServicePricingTemplate";
export const metadata:Metadata={title:{absolute:"Social Media Management Pricing in Nigeria - Monthly Packages"},description:"Compare social media management pricing in Nigeria for strategy, content creation, publishing, community management and monthly performance reporting.",keywords:["Social Media Management Pricing in Nigeria","Social Media Marketing Packages Nigeria","Social Media Management Cost Nigeria","Social Media Agency Nigeria"],alternates:{canonical:"/social-media-management-pricing/"},robots:{index:true,follow:true},openGraph:{title:"Social Media Management Pricing in Nigeria - Monthly Packages",description:"Compare monthly social media marketing packages for Nigerian businesses that need consistent content, engagement and measurable growth.",url:"/social-media-management-pricing/",siteName:"Website Designer Nigeria",type:"website",images:[{url:"/images/portfolio/Naijabeauty.png",alt:"Social media and digital brand growth project in Nigeria"}]},twitter:{card:"summary_large_image",title:"Social Media Management Pricing in Nigeria",description:"Compare monthly content and community management packages for Nigerian brands.",images:["/images/portfolio/Naijabeauty.png"]}};
const data:ServicePricingData={eyebrow:"Social Media Management Pricing in Nigeria",title:"Social Content Built",accent:"to Grow Your Brand",description:"Consistent strategy, content and community management that help Nigerian businesses earn attention and stay relevant online.",sectionLabel:"Social Media Management Pricing",sectionTitle:"Social Media Marketing Packages",sectionCopy:"How much does social media management cost in Nigeria? Compare our affordable monthly social media marketing packages.",plans:[
{name:"Starter",ngn:"80,000",usd:"70",features:["1 Social Media Platform","10 Posts per Month","Account Setup & Optimization","Content Creation","Basic Graphics Design","Community Management","Monthly Analytics Report"]},
{name:"Professional",ngn:"150,000",usd:"130",popular:true,features:["2 Social Media Platforms","15 Posts per Month","Account Setup & Optimization","Premium Content Creation","Custom Graphics & Videos","Community Management","Hashtag Strategy","Detailed Analytics & Insights"]},
{name:"Enterprise",ngn:"250,000",usd:"220",features:["3 - 4 Social Media Platforms","Daily Posts (30+ per Month)","Account Setup & Optimization","Premium Content & Videos","Custom Graphics & Videos","Story Management (Daily)","24/7 Community Management","Advanced Paid Ads Campaigns","Hashtag Strategy","Detailed Analytics & Insights","Dedicated Account Manager"]}],
faqs:[["Which social media platforms do you manage?","We manage Facebook, Instagram, X, LinkedIn, TikTok, YouTube and Pinterest. The number of platforms included depends on your package and business goals."],["What's included in content creation?","Content creation includes custom graphics, captions, relevant hashtags and scheduling. Professional and Enterprise packages also include richer video and story formats."],["Do you handle customer responses and messages?","Yes. Community management is included in every package, with the level of monitoring based on your selected plan."],["Are paid ads included in the pricing?","Paid ads management is included only in the Enterprise package, while the advertising budget remains separate."],["How do you measure success and ROI?","Monthly reports cover reach, engagement, follower growth, website clicks and other metrics linked to your business goals."],["Can I approve content before it's posted?","Yes. We share a content calendar for review and approval, and you can request revisions before scheduling."],["What other digital services do you offer?","We also provide web development, Shopify store design, SEO, email marketing and graphic design."]],benefits:[["Consistent social media requires more than filling a calendar.","Our social media management packages combine planning, creative production, publishing, conversation and performance review so every month supports a clear brand objective."],["Planned content","A structured calendar keeps your messaging consistent and aligned with campaigns."],["Active communities","Timely responses and audience engagement help build trust around your brand."],["Measurable progress","Clear monthly reporting shows what performed and what should improve next."]]};
export default function Page(){return <ServicePricingTemplate data={data}/>}








