import type {Metadata} from "next";import LegalPage,{type LegalSection} from "@/components/LegalPage";
export const metadata:Metadata={title:{absolute:"Privacy Policy - Website Designer Nigeria"},description:"Read how Website Designer Nigeria collects, uses, stores and protects personal information across our website and services.",alternates:{canonical:"/privacy-policy/"},robots:{index:true,follow:true},openGraph:{title:"Privacy Policy - Website Designer Nigeria",description:"How Website Designer Nigeria handles and protects personal information.",url:"/privacy-policy/",siteName:"Website Designer Nigeria",type:"website"}};
const sections:LegalSection[]=[
{title:"Information We Collect",items:["Personal Information: When you contact us, request a quote, or begin a project, we may collect your name, email address, phone number, business details, and other information you voluntarily provide.","Technical & Usage Data: We automatically collect information such as your IP address, browser type, device type, operating system, pages visited, and referring URLs through analytics tools.","Cookies & Tracking: We use cookies and similar technologies to personalise your experience, remember preferences, and monitor website performance. You can control cookies through your browser settings."]},
{title:"How We Use Your Information",items:["To operate and maintain our website and deliver requested services.","To respond to enquiries, schedule consultations, and provide customer support.","To manage projects, process payments, and deliver service updates or documents.","To analyse website performance and improve our user experience and services.","To send important notices, newsletters, or promotional offers with your consent; you may opt out at any time."]},
{title:"How We Share Your Information",items:["We do not sell, rent, or trade your personal data to third parties.","We may share information with trusted service providers such as hosting providers, payment processors, and email platforms, subject to confidentiality and data-protection obligations.","We may disclose personal data where required by law, court order, or to protect our legal rights or user safety."]},
{title:"Data Security",text:"We implement reasonable technical and organisational safeguards to protect your data from unauthorised access, disclosure, or misuse. No internet-based system is completely secure, so we cannot guarantee absolute security."},
{title:"Your Rights",items:["You may request access to your personal data and ask us to correct, update, or delete it where applicable.","You may withdraw consent for marketing emails or tracking cookies at any time.","To exercise your rights or request deletion, email contact@websitedesigner.ng."]},
{title:"Third-Party Links",text:"Our website may contain links to third-party websites or services. We are not responsible for their privacy practices, security, or content. Review their policies before submitting personal data."},
{title:"Children's Privacy",text:"Our services are not intended for individuals under 18. We do not knowingly collect personal information from children and will promptly delete such information if we become aware of it."},
{title:"Course & Educational Data",items:["We collect personal information and learning data to provide and improve educational services.","Certificates and achievements are linked to your account and may be verified upon request.","You retain lifetime access to all courses you have paid for."]},
{title:"Consultation Information",items:["Booking requires personal and contact details for scheduling and communication.","Session notes and recommendations are kept confidential and securely stored for follow-up.","Business and project details shared during consultations are treated as confidential.","Consultation history may support continuity and tailored recommendations in future sessions."]},
{title:"Account & Login Data",items:["We retain account credentials, login history, and session information for security and service provision.","Login attempts and access patterns may be monitored to detect fraud or unauthorised access.","Account preferences are stored to personalise your experience.","Failed login attempts and other security events may be recorded and investigated."]},
{title:"Payment & Transaction Data",items:["Payments are securely handled by KoraPay and other trusted providers.","We do not store complete card or bank-account details on our servers.","Transaction history is retained for accounting, compliance, and dispute resolution.","Verification data may be collected to prevent fraud and secure transactions.","Billing information may be shared with payment processors and financial institutions as required to complete a transaction."]},
{title:"Changes to This Policy",text:"We may update this Privacy Policy at any time. Changes will be posted on this page with an updated effective date, and we encourage you to review it periodically."},
{title:"Contact Us",text:"If you have questions or concerns about this Privacy Policy or our data practices, email contact@websitedesigner.ng."}
];
export default function Page(){return <LegalPage label="How we collect, use and protect your information." title="Privacy Policy" intro={'Website Designer Nigeria ("we," "us," or "our") is committed to respecting and protecting your privacy. This policy explains how we collect, use, store, and share information when you access www.websitedesigner.ng or engage with our services.'} sections={sections}/>}





