"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {api,getToken} from "@/lib/api";
type Course={id:number;title:string;slug:string;short_description:string|null;level:string;language:string;thumbnail:string|null;price:string;is_free:boolean;rating:string;reviews_count:number;students_count:number;lectures_count:number;total_duration:number;status:string;category:{name:string}|null;instructor:{name:string}|null};type Enrollment={course_id:number;status:string;is_paid:boolean};type Page={data:Course[];last_page:number};
const money=(course:Course)=>course.is_free?"Free":new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(Number(course.price));
const duration=(minutes:number)=>minutes>=60?`${Math.floor(minutes/60)}h${minutes%60?` ${minutes%60}m`:""}`:`${minutes||0} mins`;
const imageUrl=(path:string)=>/^https?:\/\//i.test(path)?path:`${(process.env.NEXT_PUBLIC_LEGACY_MEDIA_URL??"http://127.0.0.1:8010/media").replace(/\/$/,"")}/${path.replace(/^\/?(media\/|storage\/)?/,"")}`;
export default function CourseCatalogue(){const[courses,setCourses]=useState<Course[]>([]),[enrolled,setEnrolled]=useState<Map<number,Enrollment>>(new Map()),[state,setState]=useState<"loading"|"ready"|"error">("loading");useEffect(()=>{let active=true;(async()=>{try{const first=await api<Page>("/courses?page=1");const rest=await Promise.all(Array.from({length:Math.max(0,first.last_page-1)},(_,index)=>api<Page>(`/courses?page=${index+2}`)));if(!active)return;setCourses([...(first.data??[]),...rest.flatMap(result=>result.data??[])]);if(getToken()){try{const mine=await api<{enrollments:Enrollment[]}>("/me/courses");if(active)setEnrolled(new Map(mine.enrollments.map(item=>[item.course_id,item])))}catch{}}if(active)setState("ready")}catch{if(active)setState("error")}})();return()=>{active=false}},[]);if(state==="loading")return <div className="course-catalogue-state">Loading available courses...</div>;if(state==="error")return <div className="course-catalogue-state">Courses could not be loaded. Please refresh or contact support.</div>;if(!courses.length)return <div className="course-catalogue-state">New courses are being prepared. Please check back soon.</div>;return <div className="course-grid">{courses.map((course,index)=>{const access=enrolled.get(course.id);return <Link className="course-card-link" href={`/course/${course.slug}/`} key={course.id} aria-label={`View ${course.title}`}><article className={index===0?"featured-course":""}><div className="course-image">{course.thumbnail?<img src={imageUrl(course.thumbnail)} alt="Online Tech Courses in Nigeria"/>:<div className="course-image-fallback">WDN</div>}<span>{course.category?.name??"Technology"}</span></div><div className="course-card-body"><div className="course-card-eyebrow"><p>{course.level.replaceAll("_"," ")}</p><span>{course.language}</span></div><h2>{course.title}</h2>{course.short_description&&<p className="course-card-summary">{course.short_description}</p>}<div className="course-meta"><span>{course.lectures_count} lessons</span><span>{duration(course.total_duration)}</span><span>â˜… {Number(course.rating).toFixed(1)} ({course.reviews_count})</span><span>{course.students_count} students</span></div><div className="course-card-foot"><strong>{money(course)}</strong><span className={access?.is_paid?"course-card-enrolled":"course-card-enrol"}>{access?.is_paid?"Enrolled":course.status==="coming_soon"?"Coming soon":"Enroll now"}</span></div></div></article></Link>})}</div>}

