"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import CourseEnrollButton from "@/components/CourseEnrollButton";
import { api } from "@/lib/api";
import { ResourceFooter, ResourceHeader } from "@/components/ResourceChrome";
import CoursePinGate from "@/components/CoursePinGate";
import HelpfulReviewButton from "@/components/HelpfulReviewButton";

type Lecture={id:number;title:string;description:string|null;content:string|null;lecture_type:string;video_url:string|null;duration:number;attachments:string|null;is_preview:boolean};
type Section={id:number;title:string;description:string|null;lectures:Lecture[]};
type Instructor={name:string;bio:string|null;profile_image:string|null;expertise:string|null;years_experience:number;linkedin:string|null;twitter:string|null;website:string|null;whatsapp:string|null;rating:string;students_count:number;courses_count:number};
type Review={id:number;rating:number;review_text:string|null;helpful_count:number;is_helpful?:boolean;created_at:string;user:{username:string;first_name:string|null;last_name:string|null}};
type Course={id:number;title:string;slug:string;subtitle:string|null;short_description:string|null;description:string;level:string;language:string;thumbnail:string|null;preview_video:string|null;price:string;original_price:string|null;is_free:boolean;rating:string;reviews_count:number;students_count:number;total_duration:number;lectures_count:number;learning_objectives:string|null;prerequisites:string|null;target_audience:string|null;status:string;updated_at:string;category:{name:string;description:string|null}|null;instructor:Instructor|null;sections:Section[];reviews:Review[]};
type Access={enrolled:boolean;paid:boolean;pending:boolean;status:string|null;reviewed:boolean;can_access:boolean};

const lines=(value:string|null)=>value?.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)??[];
const money=(value:string)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(Number(value));
const mediaUrl=(path:string|null)=>{if(!path)return null;if(/^https?:\/\//i.test(path))return path;const base=process.env.NEXT_PUBLIC_LEGACY_MEDIA_URL??"http://127.0.0.1:8010/media";return `${base.replace(/\/$/,"")}/${path.replace(/^\/?(media\/|storage\/)?/,"")}`};
const nameOf=(r:Review)=>[r.user.first_name,r.user.last_name].filter(Boolean).join(" ")||r.user.username;
const initials=(r:Review)=>`${r.user.first_name?.[0]??""}${r.user.last_name?.[0]??""}`||r.user.username[0]||"W";

function Icon({name}:{name:string}){const icons:Record<string,string>={play:"M8 5v14l11-7z",clock:"M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Zm1 5h-2v6l5 3 1-1.7-4-2.3V7Z",users:"M16 11c1.7 0 3-1.3 3-3s-1.3-3-3-3-3 1.3-3 3 1.3 3 3 3ZM8 11c1.7 0 3-1.3 3-3S9.7 5 8 5 5 6.3 5 8s1.3 3 3 3Zm0 2c-2.3 0-7 1.2-7 3.5V19h14v-2.5C15 14.2 10.3 13 8 13Zm8 0c-.3 0-.7 0-1.1.1 1.2.9 2.1 2 2.1 3.4V19h6v-2.5c0-2.3-4.7-3.5-7-3.5Z",globe:"M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Zm6 7h-3c-.2-1.5-.7-2.8-1.3-4A8 8 0 0 1 18 9ZM12 4c.8 1.2 1.3 2.9 1.5 5h-3C10.7 6.9 11.2 5.2 12 4ZM4.3 14a8 8 0 0 1 0-4h4.1a17 17 0 0 0 0 4H4.3Zm.7 2h3.7c.3 1.4.7 2.7 1.3 3.7A8 8 0 0 1 5 16Zm3.7-7H5a8 8 0 0 1 5-4c-.6 1-1 2.3-1.3 4ZM12 20c-.8-1.2-1.3-2.9-1.5-4h3c-.2 1.1-.7 2.8-1.5 4Zm1.7-6h-3.4a15 15 0 0 1 0-4h3.4a15 15 0 0 1 0 4Zm.3 5.7c.6-1 1-2.3 1.3-3.7H19a8 8 0 0 1-5 3.7Zm1.6-5.7a17 17 0 0 0 0-4h4.1a8 8 0 0 1 0 4h-4.1Z",signal:"M3 21h4v-6H3v6Zm7 0h4V9h-4v12Zm7 0h4V3h-4v18Z",calendar:"M19 4h-1V2h-2v2H8V2H6v2H5a3 3 0 0 0-3 3v12a3 3 0 0 0 3 3h14a3 3 0 0 0 3-3V7a3 3 0 0 0-3-3Zm1 15H4v-8h16v8Zm0-10H4V7h16v2Z",lock:"M18 8h-1V5a5 5 0 0 0-10 0v3H6a2 2 0 0 0-2 2v12h14V10a2 2 0 0 0-2-2Zm-9-3a3 3 0 0 1 6 0v3H9V5Z",file:"M14 2H6a2 2 0 0 0-2 2v18h14V8l-6-6Zm0 3 3 3h-3V5Z"};return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={icons[name]??icons.file}/></svg>}

function SocialIcon({name}:{name:"facebook"|"x"|"linkedin"|"whatsapp"|"link"}){const paths={facebook:"M14 8h3V4h-3c-3.3 0-5 2-5 5v2H6v4h3v7h4v-7h3l1-4h-4V9c0-.7.3-1 1-1Z",x:"M18.9 3H22l-6.8 7.8L23 21h-6.1l-4.8-6.3L6.6 21H3.5l7.1-8.1L3 3h6.3l4.3 5.7L18.9 3Zm-1.1 16h1.7L8.4 4.9H6.6L17.8 19Z",linkedin:"M6.5 8.2H3V21h3.5V8.2ZM4.8 3A2.1 2.1 0 1 0 4.8 7a2.1 2.1 0 0 0 0-4ZM21 13.7c0-3.9-2.1-5.8-4.9-5.8-2.3 0-3.3 1.2-3.9 2.1V8.2H8.7V21h3.5v-6.3c0-1.7.3-3.3 2.4-3.3 2 0 2.1 1.9 2.1 3.4V21H21v-7.3Z",whatsapp:"M20.5 3.5A11.8 11.8 0 0 0 12.1 0C5.5 0 .2 5.3.2 11.9c0 2.1.6 4.1 1.6 5.9L0 24l6.4-1.7a12 12 0 0 0 5.7 1.5h.1c6.5 0 11.8-5.3 11.8-11.9 0-3.2-1.3-6.2-3.5-8.4Zm-8.4 18.3a9.8 9.8 0 0 1-5-1.4l-.4-.2-3.8 1 1-3.7-.3-.4a9.8 9.8 0 1 1 8.5 4.7Zm5.4-7.3c-.3-.2-1.8-.9-2.1-1-.3-.1-.5-.2-.7.2-.2.3-.8 1-.9 1.2-.2.2-.4.2-.7.1-2-.9-3.4-1.8-4.7-4.1-.4-.6.4-.6 1-2 .1-.2.1-.4 0-.6l-1-2.3c-.3-.6-.5-.6-.7-.6H6.6c-.3 0-.7.1-1 .5-.4.4-1.4 1.4-1.4 3.3 0 2 1.4 3.8 1.6 4.1.2.3 2.8 4.3 6.8 6 2.5 1.1 3.5 1.1 4.8.9 1.5-.2 1.8-.9 2.1-1.8.3-.8.3-1.6.2-1.8-.1-.1-.3-.2-.6-.4l-1.6-.7Z",link:"M10.6 13.4a1 1 0 0 0 1.4 1.4l4.2-4.2a3 3 0 0 0-4.2-4.2l-2.1 2.1a1 1 0 1 0 1.4 1.4l2.1-2.1a1 1 0 0 1 1.4 1.4l-4.2 4.2Zm2.8-2.8a1 1 0 0 0-1.4-1.4l-4.2 4.2a3 3 0 0 0 4.2 4.2l2.1-2.1a1 1 0 1 0-1.4-1.4l-2.1 2.1a1 1 0 0 1-1.4-1.4l4.2-4.2Z"};return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={paths[name]}/></svg>}

function TaskIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M16 4h-1.2A3 3 0 0 0 12 2a3 3 0 0 0-2.8 2H8a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2Zm-4 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2Zm-1 13-3-3 1.4-1.4 1.6 1.6 3.6-3.6L16 12l-5 5Z"/></svg>}

export default function CourseDetail(){
 const{slug}=useParams<{slug:string}>(),[course,setCourse]=useState<Course|null>(null),[access,setAccess]=useState<Access|null>(null),[state,setState]=useState<"loading"|"ready"|"error">("loading"),[pinGranted,setPinGranted]=useState(false),[tab,setTab]=useState<"overview"|"curriculum"|"reviews">("overview"),[copied,setCopied]=useState(false),[reviewBusy,setReviewBusy]=useState(false),[reviewError,setReviewError]=useState(""),[reviewSent,setReviewSent]=useState(false),[resource,setResource]=useState<Lecture|null>(null),[enrollmentSuccess,setEnrollmentSuccess]=useState(false);
 useEffect(()=>{const token=sessionStorage.getItem(`wdn_course_pin_${slug}`),query=token?`?pin_token=${encodeURIComponent(token)}`:"";api<{course:Course;access:Access}>(`/courses/${encodeURIComponent(slug)}${query}`).then(r=>{setCourse(r.course);setAccess(r.access);setPinGranted(r.course.status!=="coming_soon"||Array.isArray(r.course.sections));setState("ready")}).catch(()=>setState("error"))},[slug]);
 useEffect(()=>{const url=new URL(window.location.href);if(url.searchParams.get("enrollment")!=="successful")return;url.searchParams.delete("enrollment");window.history.replaceState({},"",`${url.pathname}${url.search}${url.hash}`);const showTimer=window.setTimeout(()=>setEnrollmentSuccess(true),0),hideTimer=window.setTimeout(()=>setEnrollmentSuccess(false),5000);return()=>{window.clearTimeout(showTimer);window.clearTimeout(hideTimer)}},[]);
 const totalLessons=useMemo(()=>course?.sections.reduce((n,s)=>n+s.lectures.length,0)??0,[course]);
 if(state==="loading")return <main className="course-detail-state">Loading course...</main>;
 if(state==="error"||!course)return <main className="course-detail-state"><h1>Course unavailable</h1><Link href="/tech-courses/">Return to courses</Link></main>;
 if(course.status==="coming_soon"&&!pinGranted)return <CoursePinGate slug={slug} title={course.title} onGranted={token=>{setState("loading");api<{course:Course;access:Access}>(`/courses/${encodeURIComponent(slug)}?pin_token=${encodeURIComponent(token)}`).then(r=>{setCourse(r.course);setAccess(r.access);setPinGranted(true);setState("ready")}).catch(()=>setState("error"))}}/>;
 const objectives=lines(course.learning_objectives),requirements=lines(course.prerequisites),audience=lines(course.target_audience),image=mediaUrl(course.thumbnail),preview=mediaUrl(course.preview_video)??course.preview_video;
 const updated=new Date(course.updated_at).toLocaleDateString("en-NG",{month:"short",year:"numeric"}),price=course.is_free?"Free":money(course.price);
 const schema={"@context":"https://schema.org","@type":"Course",name:course.title,description:course.short_description,provider:{"@type":"Organization",name:"Website Designer Nigeria",url:"https://www.websitedesigner.ng"},instructor:course.instructor?{"@type":"Person",name:course.instructor.name}:undefined,educationalLevel:course.level,courseMode:"Online",totalTime:`PT${course.total_duration}M`};
 async function submitReview(event:FormEvent<HTMLFormElement>){event.preventDefault();setReviewBusy(true);setReviewError("");const form=new FormData(event.currentTarget);try{const result=await api<{review:Review;message:string}>(`/courses/${encodeURIComponent(slug)}/reviews`,{method:"POST",body:JSON.stringify({rating:Number(form.get("rating")),review_text:String(form.get("review_text")??"")})});setCourse(previous=>previous?{...previous,reviews:[result.review,...previous.reviews],reviews_count:previous.reviews_count+1}:previous);setAccess(previous=>previous?{...previous,reviewed:true}:previous);setReviewSent(true);event.currentTarget.reset()}catch(error){setReviewError(error instanceof Error?error.message:"Your review could not be submitted.")}finally{setReviewBusy(false)}}
 return <main className="course-detail-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><ResourceHeader/>{enrollmentSuccess&&<div className="enrollment-success-toast" role="status"><span>✓</span><div><strong>Enrollment successful</strong><small>This course is now available in your account.</small></div><button type="button" onClick={()=>setEnrollmentSuccess(false)} aria-label="Dismiss notification">×</button></div>}
  <section className="cd-hero"><div className="shell cd-hero-grid"><div className="cd-hero-copy"><Link className="cd-back" href="/tech-courses/">&larr; Explore all courses</Link><p className="cd-kicker">{course.category?.name??"Online course"}</p><h1>{course.title}</h1>{course.subtitle&&<p className="cd-subtitle">{course.subtitle}</p>}<p className="cd-intro">{course.short_description}</p><div className="cd-hero-facts"><span><b>★ {Number(course.rating).toFixed(1)}</b> ({course.reviews_count} ratings)</span><span><Icon name="users"/>{course.students_count.toLocaleString()} students</span><span><Icon name="globe"/>{course.language}</span><span><Icon name="calendar"/>Updated {updated}</span><span><Icon name="signal"/>{course.level}</span></div></div>{preview?<a className="cd-visual" href={preview} target="_blank" rel="noreferrer" aria-label={`Watch the ${course.title} course preview`}>{image?<img src={image} alt={`${course.title} online course`}/>:<div className="cd-visual-fallback"><span>WDN</span><strong>{course.title}</strong></div>}<span className="cd-preview"><i><Icon name="play"/></i><span>Watch course preview<small>See what you will learn</small></span></span></a>:<div className="cd-visual">{image?<img src={image} alt={`${course.title} online course`}/>:<div className="cd-visual-fallback"><span>WDN</span><strong>{course.title}</strong></div>}</div>}</div></section>
  <nav className="cd-anchor-nav" aria-label="Course page sections"><div className="shell" role="tablist"><button className={tab==="overview"?"active":""} onClick={()=>setTab("overview")} role="tab" aria-selected={tab==="overview"}>Overview</button><button className={tab==="curriculum"?"active":""} onClick={()=>setTab("curriculum")} role="tab" aria-selected={tab==="curriculum"}>Curriculum</button><button className={tab==="reviews"?"active":""} onClick={()=>setTab("reviews")} role="tab" aria-selected={tab==="reviews"}>Reviews</button></div></nav>
  <div className="shell cd-mobile-preview-wrap">{preview?<a className="cd-visual cd-mobile-visual" href={preview} target="_blank" rel="noreferrer" aria-label={`Watch the ${course.title} course preview`}>{image?<img src={image} alt={`${course.title} online course`}/>:<div className="cd-visual-fallback"><span>WDN</span><strong>{course.title}</strong></div>}<span className="cd-preview"><i><Icon name="play"/></i><span>Watch course preview<small>See what you will learn</small></span></span></a>:<div className="cd-visual cd-mobile-visual">{image?<img src={image} alt={`${course.title} online course`}/>:<div className="cd-visual-fallback"><span>WDN</span><strong>{course.title}</strong></div>}</div>}</div>
  <section className="cd-main"><div className="shell cd-layout"><div className="cd-content">
   {tab==="overview"&&<><article id="overview" className="cd-panel cd-description"><p className="cd-label">Course overview</p><h2>Build practical skills, one clear lesson at a time.</h2><div className="cd-rich-text" dangerouslySetInnerHTML={{__html:course.description||`<p>${course.short_description??""}</p>`}}/></article>
   {objectives.length>0&&<article className="cd-panel cd-learn"><p className="cd-label">Learning outcomes</p><h2>What you will learn</h2><ul>{objectives.map(x=><li key={x}><span>✓</span><p>{x}</p></li>)}</ul></article>}
   {requirements.length>0&&<article className="cd-panel"><p className="cd-label">Before you begin</p><h2>Requirements</h2><ul className="cd-simple-list">{requirements.map(x=><li key={x}>{x}</li>)}</ul></article>}{audience.length>0&&<article className="cd-panel"><p className="cd-label">A good fit for</p><h2>Who this course is for</h2><ul className="cd-simple-list">{audience.map(x=><li key={x}>{x}</li>)}</ul></article>}
   {course.instructor&&<article className="cd-panel cd-instructor"><p className="cd-label">Meet your instructor</p><div className="cd-instructor-head">{mediaUrl(course.instructor.profile_image)?<img src={mediaUrl(course.instructor.profile_image)!} alt={`${course.instructor.name}, course instructor`}/>:<div className="cd-instructor-avatar">{course.instructor.name[0]}</div>}<div><h2>{course.instructor.name}</h2><p>{course.instructor.expertise}</p></div></div>{course.instructor.bio&&<p className="cd-instructor-bio">{course.instructor.bio}</p>}<div className="cd-socials">{course.instructor.linkedin&&<a href={course.instructor.linkedin} target="_blank" rel="noreferrer">LinkedIn</a>}{course.instructor.twitter&&<a href={course.instructor.twitter} target="_blank" rel="noreferrer">X / Twitter</a>}{course.instructor.website&&<a href={course.instructor.website} target="_blank" rel="noreferrer">Website</a>}</div></article>}</>}
   {tab==="curriculum"&&<article id="curriculum" className="cd-panel cd-curriculum"><div className="cd-heading-row"><div><p className="cd-label">Curriculum</p><h2>Course content</h2></div><p>{course.sections.length} sections Â· {totalLessons||course.lectures_count} lessons Â· {course.total_duration} minutes</p></div>{course.sections.length?course.sections.map((section,index)=><details key={section.id}><summary><span><small>Section {String(index+1).padStart(2,"0")}</small><strong>{section.title}</strong>{section.description&&<em>{section.description}</em>}</span><b>{section.lectures.length} lessons</b></summary><div className="cd-lessons">{section.lectures.map(lecture=><div className={`cd-lesson${lecture.video_url?" has-video":""}`} key={lecture.id} role={lecture.video_url?"link":undefined} tabIndex={lecture.video_url?0:undefined} onClick={()=>lecture.video_url&&window.open(lecture.video_url,"_blank","noopener,noreferrer")} onKeyDown={event=>{if(lecture.video_url&&(event.key==="Enter"||event.key===" "))window.open(lecture.video_url,"_blank","noopener,noreferrer")}}><i className={access?.can_access||lecture.is_preview?"available":"locked"}><Icon name={access?.can_access||lecture.is_preview?"play":"lock"}/></i><div><strong>{lecture.title}</strong>{lecture.description&&<p>{lecture.description}</p>}<small>{lecture.lecture_type.replaceAll("_"," ")}{lecture.duration?` Â· ${lecture.duration} min`:""}</small></div><div className="cd-lesson-actions">{(lecture.content||lecture.attachments)&&<button className="cd-resource-button" onClick={event=>{event.stopPropagation();setResource(lecture)}} aria-label={`Open task for ${lecture.title}`} title="Open task"><TaskIcon/></button>}</div></div>)}</div></details>):<div className="cd-empty"><Icon name="file"/><h3>Curriculum coming soon</h3><p>The instructor is preparing the course lessons.</p></div>}</article>}
   {tab==="reviews"&&<article id="reviews" className="cd-panel cd-reviews"><div className="cd-heading-row"><div><p className="cd-label">Student feedback</p><h2>What learners say</h2></div>{Number(course.rating)>0&&<div className="cd-rating"><b>{Number(course.rating).toFixed(1)}</b><span>{"★".repeat(Math.round(Number(course.rating)))}</span><small>{course.reviews_count} ratings</small></div>}</div>{course.reviews?.length?<div className="cd-review-grid">{course.reviews.map(review=><blockquote key={review.id}><div><i>{initials(review).toUpperCase()}</i><span><strong>{nameOf(review)}</strong><small>{new Date(review.created_at).toLocaleDateString("en-NG",{day:"numeric",month:"short",year:"numeric"})}</small></span><b>{"★".repeat(review.rating)}</b></div><p>{review.review_text}</p><HelpfulReviewButton id={review.id} count={review.helpful_count} initial={Boolean(review.is_helpful)}/></blockquote>)}</div>:<div className="cd-no-reviews"><p>No published reviews yet.</p></div>}{access?.can_access&&!reviewSent&&!access.reviewed&&<form className="cd-review-form" onSubmit={submitReview}><p className="cd-label">Your experience</p><h3>Leave a review</h3>{reviewError&&<p className="cd-review-error">{reviewError}</p>}<label>Rating<select name="rating" defaultValue="5" required><option value="5">5 — Excellent</option><option value="4">4 — Very good</option><option value="3">3 — Good</option><option value="2">2 — Fair</option><option value="1">1 — Poor</option></select></label><label>Your review<textarea name="review_text" rows={5} minLength={10} maxLength={1000} placeholder="Tell other learners about your experience..." required/></label><button disabled={reviewBusy}>{reviewBusy?"Submitting...":"Submit review"}</button></form>}{reviewSent&&<p className="cd-review-success">Thank you. Your review is now published.</p>}{!access?.can_access&&<div className="cd-review-notice"><strong>Want to leave a review?</strong><p>You must be enrolled in this course before you can share your experience.</p></div>}</article>}
  </div><aside className="cd-purchase"><p className="cd-label">Start learning</p><div className="cd-price"><strong>{price}</strong>{course.original_price&&Number(course.original_price)>Number(course.price)&&<><del>{money(course.original_price)}</del><span>Save {Math.round((1-Number(course.price)/Number(course.original_price))*100)}%</span></>}</div><CourseEnrollButton slug={course.slug} status={course.status} canAccess={Boolean(access?.can_access)} pending={Boolean(access?.pending)} isFree={course.is_free} priceLabel={price}/>{access?.can_access&&<a className="cd-whatsapp-community" href="https://chat.whatsapp.com/HyabWwIy2eXFaWbpXwXLFu" target="_blank" rel="noreferrer"><SocialIcon name="whatsapp"/> Join WhatsApp Community</a>}<div className="cd-includes"><h3>This course includes:</h3><span><Icon name="play"/>{course.total_duration>0?course.total_duration:180} minutes on-demand video</span><span><Icon name="calendar"/>1 Year course access</span><span><Icon name="file"/>Certificate of completion</span><span><Icon name="users"/>Access to course community</span><span><Icon name="signal"/>Exclusive mentorship for 1 month</span></div><div className="cd-share"><h3>Share this course</h3><div><a href={`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(`https://www.websitedesigner.ng/course/${course.slug}/`)}`} target="_blank" rel="noreferrer" aria-label="Share on Facebook"><SocialIcon name="facebook"/></a><a href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(course.title)}&url=${encodeURIComponent(`https://www.websitedesigner.ng/course/${course.slug}/`)}`} target="_blank" rel="noreferrer" aria-label="Share on X"><SocialIcon name="x"/></a><a href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(`https://www.websitedesigner.ng/course/${course.slug}/`)}`} target="_blank" rel="noreferrer" aria-label="Share on LinkedIn"><SocialIcon name="linkedin"/></a><a href={`https://wa.me/?text=${encodeURIComponent(`${course.title} https://www.websitedesigner.ng/course/${course.slug}/`)}`} target="_blank" rel="noreferrer" aria-label="Share on WhatsApp"><SocialIcon name="whatsapp"/></a><button onClick={async()=>{await navigator.clipboard.writeText(`https://www.websitedesigner.ng/course/${course.slug}/`);setCopied(true)}} aria-label="Copy course link">{copied?"âœ“":<SocialIcon name="link"/>}</button></div></div></aside></div></section>
  {resource&&<div className="cd-resource-modal" role="dialog" aria-modal="true" aria-labelledby="resource-title" onMouseDown={event=>{if(event.target===event.currentTarget)setResource(null)}}><div><button className="cd-modal-close" onClick={()=>setResource(null)} aria-label="Close task modal">Ã—</button><p className="cd-label">Lesson task &amp; resources</p><h2 id="resource-title">{resource.title}</h2>{resource.content&&<div className="cd-resource-content" dangerouslySetInnerHTML={{__html:resource.content}}/>}{resource.attachments&&<a className="cd-resource-download" href={mediaUrl(resource.attachments)!} target="_blank" rel="noreferrer"><Icon name="file"/> Download attached file</a>}</div></div>}<ResourceFooter/></main>
}
