import Image from "next/image";
import Link from "next/link";
import type { ReactNode } from "react";

const services=[["Web Development","/web-development-pricing/"],["Ecommerce Design","/ecommerce-website-design-in-nigeria/"],["Mobile App Development","/mobile-app-development-in-nigeria/"],["Shopify Design","/shopify-store-pricing/"],["SEO","/seo-pricing/"],["SM Management","/social-media-management-pricing/"],["Website Maintenance","/website-maintenance-pricing/"]];
export const resources=[["Earn Money","/earn-money/"],["Domain & Hosting","https://www.hostingnigeria.com"],["Blog","/tech-blog/"],["Book Consultation","/book-consultation/"],["Temporary Number","http://www.tempnumber.ng"]];
const portfolioImages=["owodex.png","wizzypro.png","tempnumber.png","graceempoweredearlyyears.png","Naijabeauty.png","baebronx.png","azafricanstore.png","hostingnigeria.png","Accelede.png","ladyflora.png","academia.png","debbieglitz.png"];
export function PortfolioPanels({seed}:{seed:string}){const start=[...seed].reduce((sum,char)=>sum+char.charCodeAt(0),0)%portfolioImages.length;const selected=[0,3,6,9].map(offset=>portfolioImages[(start+offset)%portfolioImages.length]);return <>{selected.map((image,index)=><div className={`floating-panel ${["panel-top-left","panel-bottom-left","panel-top-right","panel-bottom-right"][index]}`} key={image}><div className="panel-bar"><span>Selected work</span><span>•••</span></div><div className="panel-image"><Image src={`/images/portfolio/${image}`} alt="website development services" fill sizes="360px"/></div></div>)}</>}

export function ResourceHeader(){return <header className="topbar"><div className="shell nav-shell"><Link className="wordmark nav-logo" href="/"><Image src="/images/brand/footer-logo.png" alt="best web designers in Nigeria" width={210} height={48} priority/></Link><nav><Link href="/">Home</Link><div className="nav-dropdown"><span>Services⌄</span><div className="dropdown-menu">{services.map(([l,u])=><Link href={u} key={u}>{l}</Link>)}</div></div><Link href="/portfolio/">Portfolio</Link><Link href="/about-website-designer-nigeria/">About Us</Link><Link href="/tech-courses/">Courses</Link><div className="nav-dropdown"><span className="active">Resources⌄</span><div className="dropdown-menu">{resources.map(([l,u])=>u.startsWith("http")?<a href={u} target="_blank" rel="noreferrer" key={u}>{l}</a>:<Link href={u} key={u}>{l}</Link>)}</div></div><Link href="/contact-website-designer-nigeria/">Contact Us</Link></nav><Link className="profile-nav-link" href="/profile/" aria-label="My profile"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><circle cx="12" cy="8" r="4"/><path d="M4 21c0-5 3-8 8-8s8 3 8 8"/></svg></Link><a className="nav-cta" href="https://wa.me/2347075876888" target="_blank" rel="noreferrer">Start Your Project <span>→</span></a></div></header>}

export function ResourceHero({eyebrow,title,accent,description,children}:{eyebrow:string;title:string;accent:string;description:string;children?:ReactNode}){return <section className="resource-hero resource-portfolio-hero"><div className="hero-grid"/><div className="hero-halo"/><PortfolioPanels seed={`${title}-${accent}`}/><div className="shell resource-hero-inner"><div><p className="kicker">{eyebrow}</p><h1>{title}<br/><span>{accent}</span></h1><p>{description}</p><div className="hero-actions">{children}</div></div></div><div className="hero-stage"><span/><i/></div></section>}

function Social({name}:{name:string}){const p:Record<string,ReactNode>={x:<path d="M4 3h4l5 7 6-7h2l-6 9 6 9h-4l-5-7-6 7H4l7-9Z"/>,instagram:<><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/></>,youtube:<><rect x="3" y="6" width="18" height="12" rx="4"/><path d="m10 15 5-3-5-3Z"/></>,linkedin:<><rect x="3" y="9" width="4" height="12"/><circle cx="5" cy="5" r="2"/><path d="M10 21V9h4v2c1-2 7-3 7 4v6h-4v-6c0-3-3-3-3 0v6Z"/></>,tiktok:<path d="M14 3c0 3 2 4 4 4v3c-2 0-3-.5-4-1v7a5 5 0 1 1-5-5v3a2 2 0 1 0 2 2V3Z"/>};return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true">{p[name]}</svg>}
export function ResourceFooter(){return <footer className="site-footer"><div className="shell footer-grid"><div className="footer-company"><Image src="/images/brand/footer-logo.png" alt="best web designers in Nigeria" width={210} height={48}/><p>Website Designer Nigeria is a web design company in Lagos and Abuja offering website development services to ambitious businesses.</p><div className="social-links">{[["x","https://x.com/webdesignerng"],["tiktok","https://www.tiktok.com/@websitedesigner.ng"],["instagram","https://www.instagram.com/websitedesigner_ng"],["youtube","https://www.youtube.com/@websitedesignerng"],["linkedin","https://www.linkedin.com/company/website-designer-nigeria/"]].map(([n,u])=><a href={u} target="_blank" rel="noreferrer" aria-label={n} key={n}><Social name={n}/></a>)}</div></div><div><h3>Quick Links</h3><Link href="/tech-blog/">Blog</Link><Link href="/portfolio/">Portfolio</Link><Link href="/book-consultation/">Consultation</Link><Link href="/earn-money/">Affiliate Program</Link><a href="https://www.hostingnigeria.com" target="_blank" rel="noreferrer">Domain &amp; Hosting</a><a href="http://www.tempnumber.ng" target="_blank" rel="noreferrer">Temporary Number</a><Link href="/contact-website-designer-nigeria/">Contact Us</Link></div><div><h3>Our Services</h3>{services.map(([l,u])=><Link href={u} key={u}>{l}</Link>)}</div><div><h3>Contact Info</h3><a href="https://wa.me/2347075876888">07075876888</a><a href="mailto:contact@websitedesigner.ng">contact@websitedesigner.ng</a></div><div><h3>Our Offices</h3><p>Otta road, Ijora Olopa, Lagos</p><p>Jabi, Gwarinpa 900108, F.C.T Abuja</p></div></div><div className="shell footer-bottom"><p>© 2026 <Link href="/">Website Designer Nigeria</Link> by WDN Agency.</p><div><Link href="/privacy-policy/">Privacy Policy</Link><span>|</span><Link href="/terms-of-service/">Terms of Service</Link></div></div></footer>}





