import Image from "next/image";
import Link from "next/link";

export type DetailData={eyebrow:string;title:string;accent:string;description:string;introImage?:string;introTitle:string;intro:string[];features:string[][];benefitTitle:string;benefitIntro:string;benefits:string[];process?:string[][];faqs:string[][];portfolio?:string[][]};
const links=[["Web Development","/web-development-pricing/"],["Ecommerce Design","/ecommerce-website-design-in-nigeria/"],["Mobile App Development","/mobile-app-development-in-nigeria/"],["Shopify Design","/shopify-store-pricing/"],["SEO","/seo-pricing/"],["SM Management","/social-media-management-pricing/"],["Website Maintenance","/website-maintenance-pricing/"]];
const panels=[["/images/portfolio/kofoshi.png","Commerce"],["/images/portfolio/owodex.png","Product"],["/images/portfolio/ladyflora.png","Brand"],["/images/portfolio/azafricanstore.png","Growth"]];
function Social({name}:{name:string}){const p:Record<string,React.ReactNode>={x:<path d="M4 3h4l5 7 6-7h2l-6 9 6 9h-4l-5-7-6 7H4l7-9Z"/>,instagram:<><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/></>,youtube:<><rect x="3" y="6" width="18" height="12" rx="4"/><path d="m10 15 5-3-5-3Z"/></>,linkedin:<><rect x="3" y="9" width="4" height="12"/><circle cx="5" cy="5" r="2"/><path d="M10 21V9h4v2c1-2 7-3 7 4v6h-4v-6c0-3-3-3-3 0v6Z"/></>,tiktok:<path d="M14 3c0 3 2 4 4 4v3c-2 0-3-.5-4-1v7a5 5 0 1 1-5-5v3a2 2 0 1 0 2 2V3Z"/>};return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true">{p[name]}</svg>}
export default function ServiceDetailTemplate({data}:{data:DetailData}){const pathname=data.eyebrow.startsWith("Ecommerce")?"/ecommerce-website-design-in-nigeria/":"/mobile-app-development-in-nigeria/";const pageUrl=`https://www.websitedesigner.ng${pathname}`;const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:data.faqs.map(([name,text])=>({"@type":"Question",name,acceptedAnswer:{"@type":"Answer",text}}))};const serviceSchema={"@context":"https://schema.org","@type":"Service","@id":`${pageUrl}#service`,name:data.eyebrow,serviceType:data.eyebrow,description:data.description,url:pageUrl,provider:{"@type":"Organization","@id":"https://www.websitedesigner.ng/#organization",name:"Website Designer Nigeria",url:"https://www.websitedesigner.ng/"},areaServed:{"@type":"Country",name:"Nigeria"}};const breadcrumbSchema={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://www.websitedesigner.ng/"},{"@type":"ListItem",position:2,name:data.eyebrow,item:pageUrl}]};return <main className="detail-page">
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(serviceSchema)}}/>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbSchema)}}/>
<header className="topbar"><div className="shell nav-shell"><Link className="wordmark nav-logo" href="/"><Image src="/images/brand/footer-logo.png" alt="best web designers in Nigeria" width={210} height={48} priority/></Link><nav><Link href="/">Home</Link><div className="nav-dropdown"><a className="active" href="#services">Services⌄</a><div className="dropdown-menu">{links.map(([l,u])=><Link href={u} key={u}>{l}</Link>)}</div></div><Link href="/portfolio/">Portfolio</Link><Link href="/about-website-designer-nigeria/">About Us</Link><Link href="/tech-courses/">Courses</Link><div className="nav-dropdown"><span>Resources⌄</span><div className="dropdown-menu"><Link href="/earn-money/">Earn Money</Link><a href="https://www.hostingnigeria.com" target="_blank" rel="noreferrer">Buy Hosting</a><Link href="/tech-blog/">Blog</Link><Link href="/book-consultation/">Consultation</Link><Link href="/advertise-with-us/">Advertise</Link></div></div><Link href="/contact-website-designer-nigeria/">Contact Us</Link></nav><Link className="profile-nav-link" href="/profile/" aria-label="My profile"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><circle cx="12" cy="8" r="4"/><path d="M4 21c0-5 3-8 8-8s8 3 8 8"/></svg></Link><a className="nav-cta" href="https://wa.me/2347075876888" target="_blank" rel="noreferrer">Start Your Project <span>→</span></a></div></header>
<section className="hero detail-hero"><div className="hero-grid"/><div className="hero-halo"/>{panels.map(([img,label],i)=><div className={`floating-panel ${["panel-top-left","panel-bottom-left","panel-top-right","panel-bottom-right"][i]}`} key={label}><div className="panel-bar"><span>{label}</span><span>•••</span></div><div className="panel-image"><Image src={img} alt={data.eyebrow} fill sizes="360px"/></div></div>)}<div className="hero-copy shell"><p className="kicker">{data.eyebrow}</p><h1>{data.title}<br/><span>{data.accent}</span></h1><p className="hero-description">{data.description}</p><div className="hero-actions"><a className="primary-button" href="https://wa.me/2347075876888" target="_blank" rel="noreferrer">Discuss Your Project <span>→</span></a><a className="secondary-button" href="#services">Explore the Service <span>→</span></a></div></div><div className="hero-stage"><span/><i/></div></section>
<section className="detail-intro" id="services"><div className="shell detail-intro-grid"><div className="detail-intro-image"><Image src={data.introImage ?? (data.eyebrow.startsWith("Ecommerce")?"/images/portfolio/azafricanstore.png":"/images/portfolio/owodex.png")} alt={data.eyebrow} fill sizes="(max-width: 900px) 100vw, 45vw"/></div><div><p className="section-label">Built around your business</p><h2>{data.introTitle}</h2>{data.intro.map(x=><p key={x}>{x}</p>)}</div></div></section>
<section className="detail-features"><div className="shell"><div className="section-heading"><div><p className="section-label">What is included</p><h2>Features built for real customers.</h2></div><p>Every decision supports usability, dependable operations and measurable business growth.</p></div><div className="detail-feature-grid">{data.features.map(([title,copy],i)=><article key={title}><span>{String(i+1).padStart(2,"0")}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
<section className="detail-portfolio"><div className="shell"><div className="work-heading"><div><p className="section-label">Selected projects</p><h2>Relevant work from our portfolio.</h2></div><p className="work-intro">A selection of responsive websites created for Nigerian brands. Hover over a project to explore the page.</p></div><div className="work-grid">{[["Makeup Web Design","/images/portfolio/Naijabeauty.png"],["Fashion Brand Design","/images/portfolio/baebronx.png"],["E-commerce Web Design","/images/portfolio/azafricanstore.png"],["Brand Web Design","/images/portfolio/ladyflora.png"]].map(([title,img])=><article key={title}><div className="scrolling-preview"><Image src={img} alt={data.eyebrow} width={1200} height={2400} sizes="(max-width:700px) 100vw,25vw"/></div><h3>{title}</h3></article>)}</div></div></section>
<section className="detail-benefits"><div className="shell detail-benefit-layout"><div><p className="section-label">Why work with us</p><h2>{data.benefitTitle}</h2><p>{data.benefitIntro}</p></div><ul>{data.benefits.map(x=><li key={x}><span>✓</span>{x}</li>)}</ul></div></section>
<section className="pricing-faq detail-faq"><div className="shell"><div className="pricing-heading"><p>Frequently Asked Questions</p><h2>{data.eyebrow} FAQs</h2></div><div className="pricing-faq-list">{data.faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>
<section className="service-cta"><div className="shell"><p className="section-label">Start with a conversation</p><h2>Turn your idea into a product<br className="cta-heading-break"/><span> people want to use.</span></h2><p>Share your goals and we will recommend the right scope, platform and next step.</p><a className="primary-button" href="https://wa.me/2347075876888" target="_blank" rel="noreferrer">Chat on WhatsApp <span>→</span></a></div></section>
<footer className="site-footer"><div className="shell footer-grid"><div className="footer-company"><Image src="/images/brand/footer-logo.png" alt="best web designers in Nigeria" width={210} height={48}/><p>Website Designer Nigeria (WDN) is a web design company in Lagos &amp; Abuja that offers website development services. We are the best web designers in Nigeria.</p><div className="social-links">{[["x","https://x.com/webdesignerng"],["tiktok","https://www.tiktok.com/@websitedesigner.ng"],["instagram","https://www.instagram.com/websitedesigner_ng"],["youtube","https://www.youtube.com/@websitedesignerng"],["linkedin","https://www.linkedin.com/company/website-designer-nigeria/"]].map(([n,u])=><a href={u} target="_blank" rel="noreferrer" aria-label={n} key={n}><Social name={n}/></a>)}</div></div><div><h3>Quick Links</h3><Link href="/tech-courses/">Courses</Link><Link href="/portfolio/">Portfolio</Link><Link href="/about-website-designer-nigeria/">About Us</Link><Link href="/book-consultation/">Consultation</Link><Link href="/earn-money/">Affiliate Program</Link><a href="https://hostingnigeria.com">Buy Hosting</a><Link href="/contact-website-designer-nigeria/">Contact Us</Link></div><div><h3>Our Services</h3>{links.map(([l,u])=><Link href={u} key={u}>{l}</Link>)}</div><div><h3>Contact Info</h3><a href="https://wa.me/2347075876888">07075876888</a><a href="mailto:contact@websitedesigner.ng">contact@websitedesigner.ng</a></div><div><h3>Our Offices</h3><p>Otta road, Ijora Olopa, Lagos</p><p>Jabi, Gwarinpa 900108, F.C.T Abuja</p></div></div><div className="shell footer-bottom"><p>© 2026 <Link href="/">Website Designer Nigeria</Link> by WDN Agency.</p><div><Link href="/privacy-policy/">Privacy Policy</Link><span>|</span><Link href="/terms-of-service/">Terms of Service</Link></div></div></footer>
</main>}








