"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

export type Plan = { name: string; ngn: string; usd: string; features: string[]; popular?: boolean };
export type ServicePricingData = { pageClass?: string; eyebrow: string; title: string; accent: string; description: string; sectionLabel: string; sectionTitle: string; sectionCopy: string; plans: Plan[]; faqs?: string[][]; faqTitle?: string; benefits: string[][] };

const serviceLinks = [["Web Development","/web-development-pricing/"],["Ecommerce Design","/ecommerce-website-design-in-nigeria/"],["Mobile App Development","/mobile-app-development-in-nigeria/"],["Shopify Design","/shopify-store-pricing/"],["SEO","/seo-pricing/"],["SM Management","/social-media-management-pricing/"],["Website Maintenance","/website-maintenance-pricing/"]];
const panels = [["/images/portfolio/Accelede.png","Strategy"],["/images/portfolio/Naijabeauty.png","Commerce"],["/images/portfolio/fashionportfolio.png","Brand"],["/images/portfolio/aanchor.png","Growth"]];

function Social({ name }: { name: string }) { const paths:Record<string,React.ReactNode>={x:<path d="M4 3h4.6l4.25 5.7L17.8 3H20l-6.15 7.35L20.5 21h-4.6l-4.7-6.3L5.8 21H3.5l6.7-8L4 3Z"/>,instagram:<><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/></>,youtube:<><rect x="3" y="6" width="18" height="12" rx="4"/><path d="m10 15 5-3-5-3Z"/></>,linkedin:<><rect x="3" y="9" width="4" height="12"/><circle cx="5" cy="5" r="2"/><path d="M10 21V9h4v2c1-1.5 7-3 7 4v6h-4v-6c0-3-3-3-3 0v6Z"/></>,tiktok:<path d="M14 3c0 3 2 4 4 4v3c-2 0-3-.5-4-1v7a5 5 0 1 1-5-5v3a2 2 0 1 0 2 2V3Z"/>}; return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true">{paths[name]}</svg> }

export default function ServicePricingTemplate({ data }: { data: ServicePricingData }) {
  const [currency,setCurrency]=useState<"NGN"|"USD">("NGN");
  const pathname=data.eyebrow.startsWith("Shopify")?"/shopify-store-pricing/":data.eyebrow.startsWith("SEO")?"/seo-pricing/":data.eyebrow.startsWith("Website Maintenance")?"/website-maintenance-pricing/":"/social-media-management-pricing/";
  const pageUrl=`https://www.websitedesigner.ng${pathname}`;
  const serviceSchema={"@context":"https://schema.org","@type":"Service","@id":`${pageUrl}#service`,name:data.eyebrow,serviceType:data.sectionLabel,description:data.description,url:pageUrl,provider:{"@type":"Organization","@id":"https://www.websitedesigner.ng/#organization",name:"Website Designer Nigeria",url:"https://www.websitedesigner.ng/"},areaServed:{"@type":"Country",name:"Nigeria"},hasOfferCatalog:{"@type":"OfferCatalog",name:data.sectionTitle,itemListElement:data.plans.filter(plan=>!plan.ngn.startsWith("XXX")).map(plan=>({"@type":"Offer",price:plan.ngn.replaceAll(",",""),priceCurrency:"NGN",availability:"https://schema.org/InStock",url:pageUrl,itemOffered:{"@type":"Service",name:`${plan.name} - ${data.sectionLabel}`}}))}};
  const breadcrumbSchema={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://www.websitedesigner.ng/"},{"@type":"ListItem",position:2,name:data.eyebrow,item:pageUrl}]};
  return <main className={`pricing-page service-pricing-page ${data.pageClass ?? ""}`}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(serviceSchema)}}/>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbSchema)}}/>
    {data.faqs&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"FAQPage",mainEntity:data.faqs.map(([name,text])=>({"@type":"Question",name,acceptedAnswer:{"@type":"Answer",text}}))})}}/>}
    <header className="topbar"><div className="shell nav-shell"><Link className="wordmark nav-logo" href="/"><Image src="/images/brand/footer-logo.png" alt="best web designers in Nigeria" width={210} height={48} priority/></Link><nav><Link href="/">Home</Link><div className="nav-dropdown"><a className="active" href="#packages">Services⌄</a><div className="dropdown-menu">{serviceLinks.map(([label,url])=><Link href={url} key={url}>{label}</Link>)}</div></div><Link href="/portfolio/">Portfolio</Link><Link href="/about-website-designer-nigeria/">About Us</Link><Link href="/tech-courses/">Courses</Link><div className="nav-dropdown"><span>Resources⌄</span><div className="dropdown-menu"><Link href="/earn-money/">Earn Money</Link><a href="https://www.hostingnigeria.com" target="_blank" rel="noreferrer">Buy Hosting</a><Link href="/tech-blog/">Blog</Link><Link href="/book-consultation/">Consultation</Link><Link href="/advertise-with-us/">Advertise</Link></div></div><Link href="/contact-website-designer-nigeria/">Contact Us</Link></nav><Link className="profile-nav-link" href="/profile/" aria-label="My profile"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><circle cx="12" cy="8" r="4"/><path d="M4 21c0-5 3-8 8-8s8 3 8 8"/></svg></Link><a className="nav-cta" href="https://wa.me/2347075876888" target="_blank" rel="noreferrer">Start Your Project <span>→</span></a></div></header>
    <section className="hero pricing-home-hero"><div className="hero-grid"/><div className="hero-halo"/>{panels.map(([image,label],i)=><div className={`floating-panel ${["panel-top-left","panel-bottom-left","panel-top-right","panel-bottom-right"][i]}`} key={label}><div className="panel-bar"><span>{label}</span><span>•••</span></div><div className="panel-image"><Image src={image} alt={data.eyebrow} fill sizes="360px"/></div></div>)}<div className="hero-copy shell"><p className="kicker">{data.eyebrow}</p><h1>{data.title}<br/><span>{data.accent}</span></h1><p className="hero-description">{data.description}</p><div className="hero-actions"><a className="primary-button" href="#packages">View Packages <span>→</span></a><a className="secondary-button" href="https://wa.me/2347075876888" target="_blank" rel="noreferrer">Request a Quote <span>→</span></a></div></div><div className="hero-stage"><span/><i/></div></section>
    <section className="pricing-section" id="packages"><div className="shell"><div className="pricing-heading"><p>{data.sectionLabel}</p><h2>{data.sectionTitle}</h2><span>{data.sectionCopy}</span></div><div className="currency-switch"><button className={currency==="NGN"?"selected":""} onClick={()=>setCurrency("NGN")}>NGN (₦)</button><button className={currency==="USD"?"selected":""} onClick={()=>setCurrency("USD")}>USD ($)</button></div><div className="pricing-grid">{data.plans.map(plan=><article className={`pricing-card${plan.popular?" featured":""}`} key={plan.name}>{plan.popular&&<span className="popular-tag">Popular</span>}<div className="pricing-card-head"><p>{plan.name}</p><h3><small>{currency==="NGN"?"₦":"$"}</small>{currency==="NGN"?plan.ngn:plan.usd}</h3></div><ul>{plan.features.map(x=><li key={x}><span>✓</span>{x}</li>)}</ul><a href="https://wa.me/2347075876888" target="_blank" rel="noreferrer">{plan.ngn.startsWith("XXX")?"Contact Us":"Order Now"}</a></article>)}</div><p className="pricing-terms"><span className="terms-info">i</span>By ordering our services, you agree to our <Link href="/terms-of-service/">Terms of Service</Link> and <Link href="/privacy-policy/">Privacy Policy</Link>.</p></div></section>
    <section className="pricing-value"><div className="shell"><div className="pricing-value-header"><div><p className="section-label">A practical growth investment</p><h2>{data.benefits[0][0]}</h2></div><p className="pricing-value-intro">{data.benefits[0][1]}</p></div><div className="pricing-value-grid">{data.benefits.slice(1).map(([title,copy],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    {data.faqs&&<section className="pricing-faq"><div className="shell"><div className="pricing-heading"><p>Frequently Asked Questions</p><h2>{data.faqTitle ?? `${data.sectionLabel} FAQs`}</h2></div><div className="pricing-faq-list">{data.faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>}
    <section className="service-cta"><div className="shell"><p className="section-label">Ready to grow?</p><h2>Choose your package or request<br className="cta-heading-break"/><span> a tailored recommendation.</span></h2><p>Tell us what you need and we will recommend the most practical plan.</p><a className="primary-button" href="https://wa.me/2347075876888" target="_blank" rel="noreferrer">Chat on WhatsApp <span>→</span></a></div></section>
    <footer className="site-footer"><div className="shell footer-grid"><div className="footer-company"><Image src="/images/brand/footer-logo.png" alt="best web designers in Nigeria" width={210} height={48}/><p>Website Designer Nigeria (WDN) is a web design company in Lagos &amp; Abuja that offers website development services. We are the best web designers in Nigeria.</p><div className="social-links">{[["x","https://x.com/webdesignerng"],["tiktok","https://www.tiktok.com/@websitedesigner.ng"],["instagram","https://www.instagram.com/websitedesigner_ng"],["youtube","https://www.youtube.com/@websitedesignerng"],["linkedin","https://www.linkedin.com/company/website-designer-nigeria/"]].map(([n,u])=><a href={u} target="_blank" rel="noreferrer" aria-label={n} key={n}><Social name={n}/></a>)}</div></div><div><h3>Quick Links</h3><Link href="/tech-courses/">Courses</Link><Link href="/portfolio/">Portfolio</Link><Link href="/about-website-designer-nigeria/">About Us</Link><Link href="/book-consultation/">Consultation</Link><Link href="/earn-money/">Affiliate Program</Link><a href="https://hostingnigeria.com">Buy Hosting</a><Link href="/contact-website-designer-nigeria/">Contact Us</Link></div><div><h3>Our Services</h3>{serviceLinks.map(([l,u])=><Link href={u} key={u}>{l}</Link>)}</div><div><h3>Contact Info</h3><a href="https://wa.me/2347075876888">07075876888</a><a href="mailto:contact@websitedesigner.ng">contact@websitedesigner.ng</a></div><div><h3>Our Offices</h3><p>Otta road, Ijora Olopa, Lagos</p><p>Jabi, Gwarinpa 900108, F.C.T Abuja</p></div></div><div className="shell footer-bottom"><p>© 2026 <Link href="/">Website Designer Nigeria</Link> by WDN Agency.</p><div><Link href="/privacy-policy/">Privacy Policy</Link><span>|</span><Link href="/terms-of-service/">Terms of Service</Link></div></div></footer>
  </main>;
}








