import type { Metadata } from "next"; import {ResourceFooter,ResourceHeader,ResourceHero} from "@/components/ResourceChrome";
export const metadata:Metadata={title:{absolute:"Advertise With Us in Nigeria - Website Designer Nigeria"},description:"Advertise your business, products or services to Website Designer Nigeria's audience through banner ads, sponsored articles and coordinated digital campaigns.",keywords:["Advertise With Us in Nigeria","Online Advertising Nigeria","Sponsored Articles Nigeria","Website Banner Advertising"],alternates:{canonical:"/advertise-with-us/"},robots:{index:true,follow:true},openGraph:{title:"Advertise With Us in Nigeria - Website Designer Nigeria",description:"Reach entrepreneurs, professionals, students and technology-minded consumers across Nigeria.",url:"/advertise-with-us/",siteName:"Website Designer Nigeria",type:"website",images:[{url:"/images/portfolio/Accelede.png",alt:"Online advertising opportunities in Nigeria"}]},twitter:{card:"summary_large_image",title:"Advertise With Us in Nigeria",description:"Promote your brand through relevant placements and digital campaigns.",images:["/images/portfolio/Accelede.png"]}};
const options=[["Banner ads","High-visibility placements across selected pages."],["Sponsored articles","Useful, SEO-led editorial content built around your offer."],["Social campaigns","Targeted promotion through our active social channels."],["Text ads","Contextual placements integrated naturally into content."],["Popup campaigns","Focused campaigns designed to capture qualified attention."],["Newsletter inclusion","Put your brand in front of our subscriber audience."]];
export default function Page(){return <main className="resource-page"><ResourceHeader/><ResourceHero eyebrow="Reach an engaged Nigerian audience" title="Your brand deserves" accent="the right attention." description="Promote your business, products and services through thoughtful placements across Website Designer Nigeria and our social channels."><a className="primary-button" href="https://wa.me/2347075876888?text=I%20want%20to%20advertise%20with%20Website%20Designer%20Nigeria" target="_blank" rel="noreferrer">Request media options <span>→</span></a><a className="secondary-button" href="#promotion-options">Explore options</a></ResourceHero><section className="resource-light"><div className="shell resource-split"><div><p className="section-label">Advertise with us</p><h2>Meet people already looking for digital solutions.</h2></div><div><p>Website Designer Nigeria attracts entrepreneurs, professionals, students, creators and technology-minded consumers from across the country.</p><p>We shape placements around relevance and audience fit, helping your message feel useful instead of intrusive.</p></div></div><div className="shell resource-metrics">{[["10K+","Monthly visitors"],["30K+","Social followers"],["500+","Happy clients"],["24/7","Campaign support"]].map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div></section><section className="resource-dark" id="promotion-options"><div className="shell"><div className="section-heading"><div><p className="section-label">Promotion options</p><h2>A useful format for every campaign.</h2></div><p>Choose a single placement or ask us to create a coordinated package around your audience and goal.</p></div><div className="resource-option-grid">{options.map(([t,p],i)=><article key={t}><span>{String(i+1).padStart(2,"0")}</span><h3>{t}</h3><p>{p}</p></article>)}</div><div className="resource-cta"><h2>Let’s put your campaign in front of the right people.</h2><a className="primary-button" href="https://wa.me/2347075876888?text=I%20want%20to%20advertise%20with%20Website%20Designer%20Nigeria">Discuss your campaign <span>→</span></a></div></div></section><ResourceFooter/></main>}





