import type {Metadata} from "next";import LegalPage,{type LegalSection} from "@/components/LegalPage";
export const metadata:Metadata={title:{absolute:"Terms of Service - Website Designer Nigeria"},description:"Read the terms governing Website Designer Nigeria projects, payments, deliverables, intellectual property and use of our website and services.",alternates:{canonical:"/terms-of-service/"},robots:{index:true,follow:true},openGraph:{title:"Terms of Service - Website Designer Nigeria",description:"Terms governing our website, client projects, payments and service delivery.",url:"/terms-of-service/",siteName:"Website Designer Nigeria",type:"website"}};
const sections:LegalSection[]=[
{title:"Use of Our Website",items:["You must be at least 18 years old or have legal parental or guardian consent to use our services.","You agree to use our website and services only for lawful purposes.","You may not use our website or services for fraudulent, abusive, or illegal activity."]},
{title:"Intellectual Property",items:["Website content, including text, graphics, logos, and images, belongs to Website Designer Nigeria or its licensors and is protected by intellectual-property laws.","You may not reproduce, distribute, or create derivative works from our content without express written permission.","We may showcase completed projects in our portfolio unless you explicitly request otherwise in writing."]},
{title:"Service Terms",items:["Project timelines, deliverables, and fees will be agreed in writing before work begins.","Clients must provide accurate and timely information, content, access credentials, and assets required for completion.","We may pause or terminate services if a client is unresponsive, violates these Terms, or delays progress for more than 14 days without valid cause.","Revisions are limited to two rounds unless otherwise agreed. Additional changes may incur charges.","A project inactive for more than 14 consecutive days may be delayed, paused, or considered abandoned. Deposits remain non-refundable, and reactivation may require additional fees or a new agreement."]},
{title:"Payment & Refunds",items:["A non-refundable deposit, typically 70%, is required to begin work unless your agreement states otherwise.","The remaining balance is payable before final delivery or launch.","Payments over seven days late may attract a 5% weekly penalty on the outstanding balance.","Refunds are issued at our discretion based on completed work and the agreed terms."]},
{title:"Limitation of Liability",items:["We are not liable for indirect, incidental, or consequential damages arising from use of our website or services.","We are not responsible for issues caused by third-party hosting, plugins, domain registrars, or other services.","Our total liability is limited to the amount paid for the specific service concerned."]},
{title:"Post-Launch Support",items:["We offer a 14–30 day post-launch window for bug fixes and small adjustments.","Ongoing maintenance, updates, or technical support require a separate agreement or retainer."]},
{title:"Third-Party Links & Tools",text:"Our website or services may include third-party links or tools. We do not control or accept responsibility for their content, security, or availability. You use them at your own risk."},
{title:"Confidentiality",text:"Both parties agree to protect proprietary or sensitive business information shared during a project."},
{title:"Force Majeure",text:"We are not responsible for delays or failure caused by circumstances beyond our control, including natural disasters, internet outages, or government action."},
{title:"Online Courses & Educational Services",items:["Course enrolment requires full payment at purchase.","Students receive 12 months' access to purchased course materials from enrolment unless otherwise stated.","Access may be renewed through support or an extension purchase.","Certificates are issued after required modules and assessments are completed within the access period.","Course content may not be copied, shared, redistributed, or resold; violations may result in termination without refund.","Course payments are non-refundable.","We may update course content to maintain accuracy and relevance."]},
{title:"Consultation Services",items:["Consultations must be paid in advance through our secure payment system.","Session rates are ₦30,000 for 20 minutes, ₦50,000 for 40 minutes, and ₦70,000 for 60 minutes.","Sessions take place by video call, phone, or WhatsApp as selected during booking.","Rescheduling requires at least 24 hours' notice. Same-day cancellations qualify for a 50% refund.","Missed sessions are non-refundable, and late arrival does not extend the session.","Professional advice and recommendations do not guarantee specific results."]},
{title:"User Accounts & Registration",items:["Users must provide accurate, complete registration information.","You are responsible for keeping your login credentials secure.","Only one account per individual or business entity is permitted.","Notify us immediately of unauthorised access or suspicious activity.","We may suspend or terminate accounts for fraud, misuse, or violation of these Terms.","We may refuse service or terminate accounts at our discretion."]},
{title:"20 Days with WDN Tech Workshop",items:["The workshop is a free intensive programme covering web development and social media growth.","Registration requires completing the form and all pre-workshop requirements, including engagement and hosting purchase.","Participants must purchase a domain and hosting plan from hostingnigeria.com for hands-on projects.","Places are limited and not every applicant will be accepted.","Selected participants must attend scheduled sessions; repeated absence or failure to complete tasks may lead to removal.","Payments are non-refundable unless an application is not accepted.","Top performers may receive a ₦50,000 prize and paid internship opportunity.","Materials and recordings are for personal educational use and may not be shared or resold.","We may adjust schedules, curriculum, or format and will communicate significant changes.","Registration permits promotional use of participation unless the participant opts out in writing.","External partner resources remain subject to the partner's terms."]},
{title:"Login & Access Security",items:["Users must create secure passwords and remain responsible for account activity.","Account sharing and distribution of credentials are prohibited.","Repeated failed logins may trigger a temporary lockout.","We use industry-standard safeguards but cannot guarantee protection from every threat."]},
{title:"Affiliate Program Terms",items:["Approved affiliates may earn commissions by referring customers to our services and courses.","Approval is at our discretion, and affiliates receive a unique referral link or code.","Rates and payment terms are communicated upon approval and may vary by product.","Commission applies only to completed, paid transactions; refunds and cancellations do not qualify.","Requested payouts are processed within 3–5 business days, subject to a ₦30,000 minimum threshold.","Misleading advertising, spam, fraud, unauthorised brand bidding, self-referrals, and system manipulation are prohibited.","We may amend rates or programme terms and may terminate accounts with reasonable notice.","Affiliates are independent contractors. Disputes are governed by Nigerian law."]},
{title:"Social Media Management Services",items:["Management is provided monthly with a minimum 30-day commitment.","We may refuse illegal, defamatory, platform-violating, or reputation-damaging content.","Clients must provide timely account access and brand materials.","Advertising budgets are separate from management fees, and performance depends on factors outside our control.","Either party may cancel with 30 days' written notice; partial months are non-refundable.","We are not liable for suspensions, algorithm changes, or platform-policy updates outside our control."]},
{title:"Changes to These Terms",text:"We may revise these Terms from time to time. Updates will appear here with a revised effective date. Continued use after changes constitutes acceptance."},
{title:"Governing Law",text:"These Terms are governed by the laws of the Federal Republic of Nigeria, without regard to conflict-of-law provisions."},
{title:"Contact Us",text:"Questions about these Terms may be sent to contact@websitedesigner.ng."}
];
export default function Page(){return <LegalPage label="The rules governing our website, products and services." title="Terms of Service" intro={'These Terms govern your use of the Website Designer Nigeria website (www.websitedesigner.ng) and our services. By accessing or using them, you agree to these Terms. If you do not agree, please do not use our services.'} sections={sections}/>}




