import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import PricingCards from "./PricingCards";

export const metadata: Metadata = {
  title: { absolute: "Web Development Pricing in Nigeria - Website Design Packages" },
  description: "Compare transparent web development pricing and web design packages in Nigeria for corporate websites, ecommerce stores and custom platforms.",
  keywords: ["Web Development Pricing", "Web Development Pricing in Nigeria", "Web Design Packages", "Web Design Packages in Nigeria"],
  alternates: { canonical: "/web-development-pricing/" },
  robots: { index: true, follow: true },
  openGraph: { title: "Web Development Pricing in Nigeria - Website Design Packages", description: "Compare web development pricing and web design packages in Nigeria for corporate websites, ecommerce stores and custom platforms.", url: "/web-development-pricing/", siteName: "Website Designer Nigeria", type: "website", images: [{ url: "/images/portfolio/wizzypro.png", alt: "Web development and website design portfolio in Nigeria" }] },
  twitter: { card: "summary_large_image", title: "Web Development Pricing in Nigeria - Website Design Packages", description: "Compare website design packages for corporate websites, ecommerce stores and custom platforms in Nigeria.", images: ["/images/portfolio/wizzypro.png"] },
};

const faqs = [
  ["What's the best way to reach out to you?", "For the fastest response, reach us on WhatsApp: 07075876888. We're also available via email for detailed custom project inquiries. Our team is ready to discuss your web development needs and provide expert guidance!"],
  ["Can I see examples of your past work?", "Absolutely! Visit our Portfolio page to browse through our completed projects and see the quality of work we deliver. You can also request specific project examples via WhatsApp that match your industry or requirements."],
  ["Are your prices negotiable?", "We provide competitive and transparent pricing tailored to your specific requirements. Our packages are carefully structured to ensure successful project delivery while offering excellent value. We're committed to working within your budget to deliver a high-quality website that meets all your business needs."],
  ["What is included in the Custom Plan?", "The Custom Plan is designed for projects with unique or specialized requirements that go beyond our standard packages. This could include advanced integrations, complex functionality, or industry-specific features. To provide an accurate quote, we'll need comprehensive details about your project vision, required features, and business goals. Contact us to discuss your custom project!"],
  ["What post-launch support do you provide?", "We provide at least one month of extended support for all E-Commerce and Custom plan clients. This includes technical assistance, bug fixes, minor adjustments, and guidance to ensure your website runs smoothly. We're dedicated to your long-term success and remain available for ongoing maintenance services beyond the initial support period."],
  ["How long does it take to build a website?", "Development time varies by package: Corporate takes 1-2 weeks, E-Commerce takes 2-4 weeks, and Custom takes 4-6 weeks depending on complexity and specific requirements. We'll provide a detailed project timeline during our initial consultation to ensure your website launches on schedule!"],
  ["What other digital services do you offer?", "Beyond web development, we offer a comprehensive suite of digital services including Shopify Store Design, Search Engine Optimization (SEO), Social Media Management, and Mobile App Development. As a full-service digital agency, we're your one-stop solution for all online business needs."],
  ["What do your web design packages in Nigeria include?", "Our web design packages in Nigeria cover the essential design and development requirements listed under each plan. Depending on your package, this can include domain and hosting, business email, responsive pages, payment integration, analytics, SEO and post-launch support."],
];

const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) };
const serviceSchema = { "@context": "https://schema.org", "@type": "Service", "@id": "https://www.websitedesigner.ng/web-development-pricing/#service", name: "Web Development Pricing in Nigeria", serviceType: "Website Design and Development", description: "Transparent web development pricing and web design packages for Nigerian businesses.", url: "https://www.websitedesigner.ng/web-development-pricing/", provider: { "@type": "Organization", "@id": "https://www.websitedesigner.ng/#organization", name: "Website Designer Nigeria", url: "https://www.websitedesigner.ng/", telephone: "+234-707-587-6888", email: "contact@websitedesigner.ng" }, areaServed: { "@type": "Country", name: "Nigeria" }, hasOfferCatalog: { "@type": "OfferCatalog", name: "Web Development Services", itemListElement: [{ "@type": "Offer", price: "400000", priceCurrency: "NGN", availability: "https://schema.org/InStock", itemOffered: { "@type": "Service", name: "Corporate Website Package" } }, { "@type": "Offer", price: "600000", priceCurrency: "NGN", availability: "https://schema.org/InStock", itemOffered: { "@type": "Service", name: "E-Commerce Website Package" } }, { "@type": "Offer", itemOffered: { "@type": "Service", name: "Custom Web Development" } }] } };
const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://www.websitedesigner.ng/" }, { "@type": "ListItem", position: 2, name: "Web Development Pricing in Nigeria", item: "https://www.websitedesigner.ng/web-development-pricing/" }] };

function PricingPanel({ className, image, label }: { className: string; image: string; label: string }) {
  return <div className={`floating-panel ${className}`}><div className="panel-bar"><span>{label}</span><span>•••</span></div><div className="panel-image"><Image src={image} alt="web design packages in Nigeria" fill sizes="360px" /></div></div>;
}

function SocialIcon({ name }: { name: "x" | "tiktok" | "instagram" | "youtube" | "linkedin" }) {
  const icons = {
    x: <path d="M4 3h4.6l4.25 5.7L17.8 3H20l-6.15 7.35L20.5 21h-4.6l-4.7-6.3L5.8 21H3.5l6.7-8L4 3Zm3.5 1.7 9.25 14.6h1.7L9.2 4.7H7.5Z" fill="currentColor" stroke="none" />,
    tiktok: <path d="M14.2 3c.3 2.5 1.75 4 4.3 4.2v3.1a8.8 8.8 0 0 1-4.25-1.15v6.2a5.85 5.85 0 1 1-5.05-5.8v3.15a2.75 2.75 0 1 0 1.85 2.6V3h3.15Z" fill="currentColor" stroke="none" />,
    instagram: <><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></>,
    youtube: <><path d="M21 8.2a3 3 0 0 0-2.1-2.1C17 5.6 12 5.6 12 5.6s-5 0-6.9.5A3 3 0 0 0 3 8.2a31 31 0 0 0-.5 3.8A31 31 0 0 0 3 15.8a3 3 0 0 0 2.1 2.1c1.9.5 6.9.5 6.9.5s5 0 6.9-.5a3 3 0 0 0 2.1-2.1 31 31 0 0 0 .5-3.8 31 31 0 0 0-.5-3.8Z"/><path d="m10 15 5-3-5-3v6Z" fill="currentColor" stroke="none"/></>,
    linkedin: <><rect x="3" y="9" width="4" height="12" fill="currentColor" stroke="none"/><circle cx="5" cy="5" r="2" fill="currentColor" stroke="none"/><path d="M10 21V9h4v1.8c1-1.4 2.4-2.2 4-2 2.5.3 3 2.3 3 5.2v7h-4v-6.2c0-1.5-.4-2.6-1.7-2.6-1.5 0-1.8 1.2-1.8 2.9V21H10Z" fill="currentColor" stroke="none"/></>,
  };
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{icons[name]}</svg>;
}

export default function WebDevelopmentPricingPage() {
  return <main className="pricing-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
    <header className="topbar"><div className="shell nav-shell"><Link className="wordmark nav-logo" href="/"><Image src="/images/brand/footer-logo.png" alt="best web designers in Nigeria" width={210} height={48} priority /></Link><nav><Link href="/">Home</Link><div className="nav-dropdown"><a className="active" href="#pricing">Services⌄</a><div className="dropdown-menu"><Link href="/web-development-pricing/">Web Development</Link><Link href="/ecommerce-website-design-in-nigeria/">Ecommerce Design</Link><Link href="/mobile-app-development-in-nigeria/">Mobile App Development</Link><Link href="/shopify-store-pricing/">Shopify Design</Link><Link href="/seo-pricing/">SEO</Link><Link href="/social-media-management-pricing/">SM Management</Link><Link href="/website-maintenance-pricing/">Website Maintenance</Link></div></div><Link href="/portfolio/">Portfolio</Link><Link href="/about-website-designer-nigeria/">About Us</Link><Link href="/tech-courses/">Courses</Link><div className="nav-dropdown"><span>Resources⌄</span><div className="dropdown-menu"><Link href="/earn-money/">Earn Money</Link><a href="https://www.hostingnigeria.com" target="_blank" rel="noreferrer">Buy Hosting</a><Link href="/tech-blog/">Blog</Link><Link href="/book-consultation/">Consultation</Link><Link href="/advertise-with-us/">Advertise</Link></div></div><Link href="/contact-website-designer-nigeria/">Contact Us</Link></nav><Link className="profile-nav-link" href="/profile/" aria-label="My profile"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><circle cx="12" cy="8" r="4"/><path d="M4 21c0-5 3-8 8-8s8 3 8 8"/></svg></Link><a className="nav-cta" href="mailto:contact@websitedesigner.ng">Contact Us <span>→</span></a></div></header>
    <section className="hero pricing-home-hero"><div className="hero-grid" aria-hidden="true"/><div className="hero-halo" aria-hidden="true"/><PricingPanel className="panel-top-left" image="/images/portfolio/wizzypro.png" label="Photography"/><PricingPanel className="panel-bottom-left" image="/images/portfolio/owodex.png" label="Fintech"/><PricingPanel className="panel-top-right" image="/images/portfolio/tempnumber.png" label="Technology"/><PricingPanel className="panel-bottom-right" image="/images/portfolio/graceempoweredearlyyears.png" label="Education"/><div className="hero-copy shell"><p className="kicker">Web Design Packages in Nigeria</p><h1>Clear Web Development<br/><span>Pricing for Every Ambition</span></h1><p className="hero-description">Explore practical web design packages for corporate websites, ecommerce stores and custom platforms.<br className="desktop-only"/> Choose a starting point, then we will tailor the scope to your business.</p><div className="hero-actions"><a className="primary-button" href="#pricing">View Packages <span>→</span></a><a className="secondary-button" href="https://wa.me/2347075876888" target="_blank" rel="noreferrer">Request a Quote <span>→</span></a></div></div><div className="hero-stage" aria-hidden="true"><span/><i/></div></section>
    <section className="pricing-section" id="pricing"><div className="shell"><div className="pricing-heading"><p>Web Design Packages in Nigeria</p><h2>Web Development Pricing</h2><span>Compare our web development pricing in Nigeria. Each package provides a clear starting scope, while your final quote reflects the pages, features, integrations and support your project requires.</span></div><PricingCards/><p className="pricing-terms"><span className="terms-info" aria-hidden="true">i</span>By ordering our services, you agree to our <Link href="/terms-of-service/">Terms of Service</Link> and <Link href="/privacy-policy/">Privacy Policy</Link>.</p></div></section>
    <section className="pricing-value"><div className="shell"><div className="pricing-value-header"><div><p className="section-label">What every package delivers</p><h2>Web design packages built for credibility, speed and growth.</h2></div><p className="pricing-value-intro">Our web development pricing is structured around real business needs—not arbitrary page templates. Every project receives responsive design, a dependable technical foundation and direct support from our Nigerian team.</p></div><div className="pricing-value-grid"><article><span>01</span><h3>Responsive by default</h3><p>Your website is carefully designed for mobile, tablet and desktop visitors.</p></article><article><span>02</span><h3>SEO-ready foundations</h3><p>Clean structure and on-page essentials give your visibility a stronger starting point.</p></article><article><span>03</span><h3>Direct expert support</h3><p>You work with a Nigerian web development team before, during and after launch.</p></article></div></div></section>
    <section className="pricing-faq"><div className="shell"><div className="pricing-heading"><p>Frequently Asked Questions</p><h2>Web Development Pricing FAQs</h2></div><div className="pricing-faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>
    <section className="service-cta"><div className="shell"><p className="section-label">Have a project in mind?</p><h2>Choose a package or request{" "}<br className="cta-heading-break"/><span>a tailored recommendation.</span></h2><p>Tell us what you need and we will help you select the most practical option.</p><a className="primary-button" href="https://wa.me/2347075876888" target="_blank" rel="noreferrer">Chat on WhatsApp <span>→</span></a></div></section>
    <footer className="site-footer"><div className="shell footer-grid"><div className="footer-company"><Image src="/images/brand/footer-logo.png" alt="best web designers in Nigeria" width={210} height={48}/><p>Website Designer Nigeria (WDN) is a web design company in Lagos &amp; Abuja that offers website development services. We are the best web designers in Nigeria.</p><div className="social-links"><a href="https://x.com/webdesignerng" target="_blank" rel="noreferrer" aria-label="X"><SocialIcon name="x"/></a><a href="https://www.tiktok.com/@websitedesigner.ng" target="_blank" rel="noreferrer" aria-label="TikTok"><SocialIcon name="tiktok"/></a><a href="https://www.instagram.com/websitedesigner_ng" target="_blank" rel="noreferrer" aria-label="Instagram"><SocialIcon name="instagram"/></a><a href="https://www.youtube.com/@websitedesignerng" target="_blank" rel="noreferrer" aria-label="YouTube"><SocialIcon name="youtube"/></a><a href="https://www.linkedin.com/company/website-designer-nigeria/" target="_blank" rel="noreferrer" aria-label="LinkedIn"><SocialIcon name="linkedin"/></a></div></div><div><h3>Quick Links</h3><Link href="/tech-courses/">Courses</Link><Link href="/portfolio/">Portfolio</Link><Link href="/about-website-designer-nigeria/">About Us</Link><Link href="/book-consultation/">Consultation</Link><Link href="/earn-money/">Affiliate Program</Link><a href="https://hostingnigeria.com">Buy Hosting</a><Link href="/contact-website-designer-nigeria/">Contact Us</Link></div><div><h3>Our Services</h3><Link href="/web-development-pricing/">Web Development</Link><Link href="/shopify-store-pricing/">Shopify Design</Link><Link href="/seo-pricing/">SEO</Link><Link href="/social-media-management-pricing/">SM Management</Link><Link href="/website-maintenance-pricing/">Website Maintenance</Link></div><div><h3>Contact Info</h3><a href="https://wa.me/2347075876888">07075876888</a><a href="mailto:contact@websitedesigner.ng">contact@websitedesigner.ng</a></div><div><h3>Our Offices</h3><p>Otta road, Ijora Olopa, Lagos</p><p>Jabi, Gwarinpa 900108, F.C.T Abuja</p></div></div><div className="shell footer-bottom"><p>© 2026 <Link href="/">Website Designer Nigeria</Link> by WDN Agency.</p><div><Link href="/privacy-policy/">Privacy Policy</Link><span>|</span><Link href="/terms-of-service/">Terms of Service</Link></div></div></footer>
  </main>;
}








